### ISSUE TITLE
ImmutableStore

### ISSUE THREAD

**Issue by edbo** [yahoo/fluxible-immutable-utils#26]
Hi Guys,

Like the work you were doing here but I wanted to esSixify the repo, in particular the store such that it inherits a base class rather than creates a store using a wrapper.

This allows me to define a store like this which seems cleaner imo:

```
import {ImmutableStore} from 'fluxible-immutable-utils';

class ContentStore extends ImmutableStore {
	contentReceived(content) {
		this.setState(content);
		this.emitChange();
	}
}

ContentStore.storeName = 'ContentStore';
ContentStore.handlers = {
	GET_CONTENT_SUCCESS: 'contentReceived'
};

export default ContentStore;
```

The commit I made is here: https://github.com/bitgaming/fluxible-immutable-utils/commit/c7ec8212d2a9115498236bf93117f0c7981d63b0

This isn't ready to be merged in as it would need the following problems fixed:

* Linter breaks on the Class keyword in the ImmutabeStore as it will need to pull in Babel somehow
* It should have the createImmutabeStore.js file deleted since the code is completely duplicated
* It needs the readme updated

If you guys are interested I can make further commits to rectify the above but before I do I guess I just wanted to know are you guys even interested in this approach or do you prefer not to have es6 classes yet?

**Comment by 3den** [comment]
I like that, @akshayp @dmhood what do you guys think?

**Comment by dmhood** [comment]
Sounds good to me

**Comment by edbo** [comment]
One comment I would make is the only way I can think of making this work properly with node as it stands would be to include a build script that converts the es6 code to es5 compatible code which is what would get included when people npm install.

The other option would be to use something like iojs with the  --harmony_classes flag set (I haven't actually tried this yet). I am thinking the harmony approach would cause more issues in the short term though anyway and more compatibility would be better.

**Comment by edbo** [comment]
Oh do you guys a preferred build tool (gulp/grunt/other...)?

**Comment by 3den** [comment]
@edbo we usually use grunt at yahoo, but if you prefer gulp it should be fine too.

**Comment by edbo** [comment]
Replacing with this https://github.com/yahoo/fluxible-immutable-utils/pull/27
