### ISSUE TITLE
Is mergeState an official method?

### ISSUE THREAD

**Issue by DullReferenceException** [yahoo/fluxible-immutable-utils#39]
We've been enjoying `createImmutableStore`. It provides a really useful `.mergeState` method. However, this method is not _documented_. Is this a safe method for us to be using, or will it be going away? If it's safe to use, it'd be great if it was mentioned in the docs.

**Comment by koulmomo** [comment]
@DullReferenceException anything not inside of the [`internals`](https://github.com/yahoo/fluxible-immutable-utils/tree/master/internals) dir is considered "blessed" and any non-bc changes will be treated as `breaking`. 

there definitely needs to be better documentation for [sure](https://github.com/yahoo/fluxible-immutable-utils/issues/30) ;)
