### ISSUE TITLE
[createImmutableContainer] Got error: object is not a function

### ISSUE THREAD

**Issue by tom76kimo** [yahoo/fluxible-immutable-utils#42]
After doing this:

``` javascript
module.exports = createImmutableContainer(MyComponent, {
    stores: [SomeStore],
    getStateFromStores: {
        SomeStore: function (store) {
            return {
                someState: store.state;
            }
        }
    }
});
```

received the error since `getStateFromStores` is an object, but `connectToStore` [treats it as a function](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-addons-react/connectToStores.js#L19).

**Comment by tom76kimo** [comment]
Ah, just found [connectToStores](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-addons-react/connectToStores.js). So `createImmutableContainer ` is deprecated, right?

**Comment by 3den** [comment]
It is not deprecated yet but is not that useful because it only deals with props. On some projects i have implemented a decorator instead of that

**Comment by tom76kimo** [comment]
Thanks
