### ISSUE TITLE
React lib reference

### ISSUE THREAD

**Issue by gingur** [yahoo/fluxible-immutable-utils#43]
The code @ https://github.com/yahoo/fluxible-immutable-utils/blob/master/lib/createImmutableContainer.js#L12 is referencing the React tree structure directly, this breaks client implementations that are using React from a CDN or are bundling with webpack using the `dist/react.min.js` alias.

**Comment by koulmomo** [comment]
it  should be as simple as replacing that call to using the standalone npm package https://www.npmjs.com/package/react-addons-shallow-compare instead

**Comment by roderickhsiao** [comment]
:+1:

**Comment by gingur** [comment]
@koulmomo correct me if I'm wrong, but that wouldn't work either.. that simply returns `module.exports = require('react/lib/shallowCompare');` which would again require the react lib to be available as a node_module.
